# Generated by Django 2.0 on 2020-11-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
